version: '3.9'

services:
  cold-db:
    image: postgres:13.9-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ../../.db:/var/lib/postgresql/data
    networks:
      - internal

  object-storage:
    image: minio/minio
    restart: unless-stopped
    entrypoint: minio server /data
    environment:
      MINIO_ROOT_USER: 'user'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_BUCKET: 'bucket'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ../../.objects:/data
    networks:
      - internal

  server-app:
    build:
      context: ../..
      dockerfile: deployments/dev/Dockerfile
    restart: unless-stopped
    environment:
      HOST: '0.0.0.0'
      DATABASE_URL: 'postgres://user:password@cold-db/database'
      S3_ACCESS_KEY: 'user'
      S3_SECRET_KEY: 'password'
      S3_BUCKET: 'bucket'
      S3_ENDPOINT: 'http://object-storage:9000'
    ports:
      - '3000:3000'
    volumes:
      - ../../:/app
    working_dir: /app
    depends_on:
      - cold-db
      - object-storage
    command: tail -f /dev/null
    networks:
      - internal

networks:
  internal:
    external: true
